In [1]:
import torch
a = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.int32)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [2]:
import torch
a = torch.linspace(-1, 1, 10)
print(a)

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])


In [3]:
import torch
a = torch.rand(3,4)
print(a)

tensor([[0.9106, 0.9658, 0.7207, 0.0508],
        [0.2962, 0.2731, 0.0012, 0.2440],
        [0.3257, 0.0132, 0.5924, 0.1216]])


In [4]:
import torch
a = torch.randn(3,4)
print(a)

tensor([[-0.8753,  0.3626, -0.9982,  0.0173],
        [ 0.5748, -1.4338, -1.3449,  0.3395],
        [ 1.2474, -0.3639,  1.0106, -0.1456]])


In [5]:
import torch
a = torch.randint(3, 10, size=(3,4))
print(a)

tensor([[8, 8, 9, 5],
        [7, 3, 3, 8],
        [9, 5, 4, 6]])


In [6]:
import torch
a = torch.randint(10, size=(3,4))
print(a)

tensor([[6, 6, 6, 1],
        [8, 6, 8, 9],
        [2, 3, 6, 4]])


In [7]:
import torch
a = torch.zeros(2, 3, 4)
print(a)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [8]:
import torch
a = torch.full((2,3,4), 5)
print(a)

tensor([[[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]],

        [[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]]])


In [9]:
import torch
a = torch.ones(2,3,4)
print(a)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [10]:
import torch
a = torch.eye(4)
print(a)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [11]:
import torch
a = torch.zeros(2, 3, 4)
print(a.shape)
print(a.size())

torch.Size([2, 3, 4])
torch.Size([2, 3, 4])


In [12]:
import torch
a = torch.zeros(2, 3, 4)
print(a.shape)
print(a.size())

torch.Size([2, 3, 4])
torch.Size([2, 3, 4])


In [13]:
import torch
a = torch.zeros(2, 3, 4)
print(a.ndim)

3


In [14]:
import torch
a = torch.zeros(2, 3, 4)
print(len(a))

2


In [15]:
import torch
a = torch.zeros(2, 3, 4)
print(a.dtype)

torch.float32


In [16]:
import torch
a = torch.zeros(2, 3, 4)
b = a.type(torch.int32)
print(a.dtype)
print(b.dtype)

torch.float32
torch.int32


In [17]:
import torch
a = torch.randn(3,4,5)
print(a)

tensor([[[-0.9052, -0.6610, -1.4753,  1.4577, -0.9539],
         [ 0.2726,  0.6008, -1.4087, -2.3441, -0.1081],
         [-1.3323, -0.8763, -0.1875,  0.2993, -1.3787],
         [-0.4889, -1.6824, -1.7948,  0.1996,  0.8502]],

        [[ 0.8399,  0.3186, -1.1640, -0.6596, -0.7094],
         [-0.2520, -0.8516, -1.6511, -0.6303,  0.1623],
         [-0.8515, -0.6394,  0.4850, -0.1015,  0.1301],
         [-0.7989,  1.0747, -0.8461,  1.3353, -1.1586]],

        [[ 0.6809, -1.9761, -0.6979, -0.6897,  0.6027],
         [ 0.2671,  0.7514,  1.1401,  1.0677, -0.0669],
         [-0.1178, -1.0199, -1.7064, -0.5079,  0.2632],
         [-1.0902,  0.5334, -1.9930, -0.0967, -0.0088]]])


In [18]:
import torch
a = torch.randn(3,4,5)
print(a)
print(a[1])

tensor([[[-0.8925, -1.7286,  0.5537, -0.2027, -0.5581],
         [ 0.6581, -2.4330, -1.1947, -0.6524, -1.1140],
         [-1.0761,  1.8084, -0.9315, -0.0490, -0.7119],
         [-0.0952,  0.3063, -0.4900, -1.4745, -0.7054]],

        [[-1.4231,  0.4714,  0.1329, -1.7768,  0.3669],
         [ 1.9575, -0.3662,  1.6436, -0.1418,  2.0764],
         [ 0.8061,  0.1376, -2.0499, -0.9899, -0.2721],
         [ 1.6550,  0.6887, -1.1845,  0.5528, -1.5345]],

        [[ 0.4045, -0.6399,  0.5677,  0.9356, -0.2312],
         [ 0.4145, -0.5022, -2.0844,  1.9006, -0.6685],
         [ 1.2025,  0.1772,  0.5407, -1.5444, -0.0823],
         [-0.0223,  0.6645,  1.1577,  0.3977,  0.5596]]])
tensor([[-1.4231,  0.4714,  0.1329, -1.7768,  0.3669],
        [ 1.9575, -0.3662,  1.6436, -0.1418,  2.0764],
        [ 0.8061,  0.1376, -2.0499, -0.9899, -0.2721],
        [ 1.6550,  0.6887, -1.1845,  0.5528, -1.5345]])


In [19]:
import torch
a = torch.randn(3,4,5)
print(a)
print(a[1:, 2:4])

tensor([[[ 0.3256, -0.7917,  0.4358,  0.6991,  0.2874],
         [-1.0274, -0.0968, -0.4584,  1.1036,  0.1943],
         [-1.6825,  0.9952,  0.8378,  1.4208,  0.9234],
         [ 2.0475,  0.4257, -0.5434, -0.4868, -1.8695]],

        [[-0.6175,  0.5665,  0.2104, -2.6057,  1.3916],
         [-0.8109, -0.4705,  0.7020, -0.3140,  2.6800],
         [ 0.7425, -0.5055, -0.6863, -0.1969,  0.3796],
         [-1.1579,  0.5342,  1.1177, -1.6662, -0.7281]],

        [[-0.0351, -0.4017,  0.5972,  0.8692,  0.0654],
         [-1.6295, -0.2976,  0.1009, -0.9068, -1.8245],
         [-1.0806, -1.5656,  1.3698,  0.5280, -0.3302],
         [ 0.2242,  0.5044,  1.2398, -0.3688, -1.5030]]])
tensor([[[ 0.7425, -0.5055, -0.6863, -0.1969,  0.3796],
         [-1.1579,  0.5342,  1.1177, -1.6662, -0.7281]],

        [[-1.0806, -1.5656,  1.3698,  0.5280, -0.3302],
         [ 0.2242,  0.5044,  1.2398, -0.3688, -1.5030]]])


In [20]:
import torch
a = torch.randn(3,4,5)
print(a)
print(a[:, None, :, None].shape)

tensor([[[ 0.3990, -2.0785, -0.5009, -0.2367,  0.9503],
         [-0.6587,  0.2589,  0.9660,  1.2761, -0.8621],
         [ 0.2977, -0.3140, -0.7156, -1.1456,  1.0825],
         [-1.7327,  0.2015, -3.0135, -0.8271,  0.6363]],

        [[ 0.2033, -0.2312,  0.1269,  3.3219, -0.6579],
         [-1.2189, -0.5636,  1.6760, -1.2951, -0.4658],
         [-0.9911,  0.7130, -0.7271, -1.0968,  0.8316],
         [ 0.6432,  0.8200, -0.7724,  1.6419,  0.8102]],

        [[ 1.4380, -1.7483, -0.7106,  0.0411, -0.3710],
         [ 0.1929, -2.0073, -0.9794, -1.4790,  2.0803],
         [ 0.6713,  1.4788,  0.4919, -0.7207, -1.1359],
         [-1.0546,  0.0433, -0.4026,  0.1114, -0.8051]]])
torch.Size([3, 1, 4, 1, 5])


In [21]:
import torch
a = torch.randn(3,4,5)
b = torch.unsqueeze(a, dim=2)
print(a.shape)
print(b.shape)

torch.Size([3, 4, 5])
torch.Size([3, 4, 1, 5])


In [22]:
import torch
a = torch.randn(3,4)
print(a)
print(a[:, (a > -1).all(axis=0)])

tensor([[ 0.9358,  1.3662,  0.6332, -1.2814],
        [-2.9179,  0.1243, -0.4656,  1.3730],
        [-0.7992,  0.2039, -0.6329, -0.3922]])
tensor([[ 1.3662,  0.6332],
        [ 0.1243, -0.4656],
        [ 0.2039, -0.6329]])


In [23]:
import torch
a = torch.randn(3,4)
print(a)
print(a[:, [1,0,0,1]])

tensor([[-0.0647,  0.7601,  0.1197,  0.7736],
        [-1.3061,  1.0992,  0.2055,  0.5907],
        [-0.9918,  1.2611, -0.1345, -1.0298]])
tensor([[ 0.7601, -0.0647, -0.0647,  0.7601],
        [ 1.0992, -1.3061, -1.3061,  1.0992],
        [ 1.2611, -0.9918, -0.9918,  1.2611]])


In [24]:
import torch
a = torch.randn(3,4)
print(a)
print(a.ravel())

tensor([[ 1.6895, -0.6829, -1.2877, -0.4646],
        [-0.8258, -0.3087,  0.6710, -1.2514],
        [ 2.2484, -0.9899, -0.6311, -0.0721]])
tensor([ 1.6895, -0.6829, -1.2877, -0.4646, -0.8258, -0.3087,  0.6710, -1.2514,
         2.2484, -0.9899, -0.6311, -0.0721])


In [25]:
import torch
a = torch.randn(3,4)
print(a)
print(a.reshape(-1))

tensor([[-0.2363, -1.3105,  0.0802, -1.6061],
        [ 0.8676, -0.2772, -1.3186,  0.9434],
        [ 0.3752, -1.5436, -1.3148,  0.7299]])
tensor([-0.2363, -1.3105,  0.0802, -1.6061,  0.8676, -0.2772, -1.3186,  0.9434,
         0.3752, -1.5436, -1.3148,  0.7299])


In [26]:
import torch
a = torch.randn(3,4)
print(a)
print(a.reshape(3,2,2))

tensor([[ 0.2913,  0.1363,  0.5490, -0.3372],
        [ 0.4855, -1.4106,  0.3460, -1.4702],
        [-1.0590, -0.3552,  1.3861, -0.9552]])
tensor([[[ 0.2913,  0.1363],
         [ 0.5490, -0.3372]],

        [[ 0.4855, -1.4106],
         [ 0.3460, -1.4702]],

        [[-1.0590, -0.3552],
         [ 1.3861, -0.9552]]])


In [27]:
import torch
a = torch.randn(3,4)
print(a)
print(a.T)

tensor([[ 0.6187,  0.5648, -0.2976,  0.4986],
        [-0.8138, -0.4105,  1.7102, -1.6538],
        [-1.8045, -0.0096, -1.1592,  1.2436]])
tensor([[ 0.6187, -0.8138, -1.8045],
        [ 0.5648, -0.4105, -0.0096],
        [-0.2976,  1.7102, -1.1592],
        [ 0.4986, -1.6538,  1.2436]])


In [28]:
import torch
a = torch.randn(3,4)
print(a)
print(a.T)

tensor([[ 1.7258, -1.4121,  0.6175, -0.3053],
        [-0.4952, -0.3424,  1.3843,  1.1435],
        [-0.3791, -0.6561,  0.0299,  0.5562]])
tensor([[ 1.7258, -0.4952, -0.3791],
        [-1.4121, -0.3424, -0.6561],
        [ 0.6175,  1.3843,  0.0299],
        [-0.3053,  1.1435,  0.5562]])


In [29]:
import torch
a = torch.randn(3,3)
b = torch.randn(3,3)
print(a)
print(b)
print(torch.vstack([a,b]))

tensor([[-1.1830, -0.4215,  1.4908],
        [ 0.5652,  0.4646,  0.1923],
        [-2.0611,  0.8266, -1.7769]])
tensor([[-2.0617,  0.7068, -0.1873],
        [-0.3563, -1.1593, -1.4898],
        [ 0.6174, -0.2865,  0.5685]])
tensor([[-1.1830, -0.4215,  1.4908],
        [ 0.5652,  0.4646,  0.1923],
        [-2.0611,  0.8266, -1.7769],
        [-2.0617,  0.7068, -0.1873],
        [-0.3563, -1.1593, -1.4898],
        [ 0.6174, -0.2865,  0.5685]])


In [30]:
import torch
a = torch.randn(3,3)
b = torch.randn(3,3)
c = torch.concatenate([a, b])
print(a)
print(b)
print(c)

tensor([[-0.5303, -0.2629,  0.5077],
        [-0.4788,  1.2553, -0.6467],
        [-3.6099, -0.8485, -0.2728]])
tensor([[ 1.4528,  2.3452,  1.6118],
        [ 1.5532, -1.1360,  0.3834],
        [ 0.7452,  0.4315, -1.4492]])
tensor([[-0.5303, -0.2629,  0.5077],
        [-0.4788,  1.2553, -0.6467],
        [-3.6099, -0.8485, -0.2728],
        [ 1.4528,  2.3452,  1.6118],
        [ 1.5532, -1.1360,  0.3834],
        [ 0.7452,  0.4315, -1.4492]])


In [31]:
import torch
a = torch.randn(3,3)
b = torch.randn(3,3)
c = torch.concatenate([a, b])
print(a)
print(b)
print(c)

tensor([[ 0.5899,  0.4960, -0.5495],
        [ 0.6104, -0.3334, -0.4252],
        [ 0.4975,  1.3262,  0.8651]])
tensor([[-1.2698,  0.5076,  0.5166],
        [-1.2880, -1.1573,  0.4146],
        [ 1.7367,  1.0277,  0.1778]])
tensor([[ 0.5899,  0.4960, -0.5495],
        [ 0.6104, -0.3334, -0.4252],
        [ 0.4975,  1.3262,  0.8651],
        [-1.2698,  0.5076,  0.5166],
        [-1.2880, -1.1573,  0.4146],
        [ 1.7367,  1.0277,  0.1778]])


In [32]:
import torch
a = torch.randn(3,3)
b = torch.randn(3,3)
c = torch.concatenate([a, b])
print(c)
print(torch.split(c, 3, dim=0))

tensor([[ 0.7283,  0.6986,  0.2257],
        [ 0.5408,  1.3465,  0.6147],
        [ 0.0345, -1.9646,  1.7291],
        [-0.0321,  0.2753,  1.0789],
        [-0.0882, -0.6564,  0.2305],
        [ 0.6776, -0.5438,  1.1108]])
(tensor([[ 0.7283,  0.6986,  0.2257],
        [ 0.5408,  1.3465,  0.6147],
        [ 0.0345, -1.9646,  1.7291]]), tensor([[-0.0321,  0.2753,  1.0789],
        [-0.0882, -0.6564,  0.2305],
        [ 0.6776, -0.5438,  1.1108]]))


In [33]:
import torch
a = torch.randn(2,3)
print(a)
print("exp =", torch.exp(a))
print("log =", torch.log(a))
print("sin =", torch.sin(a))
print("arctan =", torch.arctan(a))
print("abs =", torch.abs(a))
print("square =", torch.square(a))
print("sqrt =", torch.sqrt(a))
print("ceil =", torch.ceil(a))
print("round =", torch.round(a))
print("clip =", torch.clip(a, 0.1, 0.9))

tensor([[ 1.1729,  0.8480, -1.8110],
        [-0.0711, -0.7760,  1.1232]])
exp = tensor([[3.2313, 2.3349, 0.1635],
        [0.9313, 0.4603, 3.0747]])
log = tensor([[ 0.1595, -0.1649,     nan],
        [    nan,     nan,  0.1162]])
sin = tensor([[ 0.9219,  0.7499, -0.9713],
        [-0.0711, -0.7004,  0.9015]])
arctan = tensor([[ 0.8648,  0.7033, -1.0663],
        [-0.0710, -0.6599,  0.8434]])
abs = tensor([[1.1729, 0.8480, 1.8110],
        [0.0711, 0.7760, 1.1232]])
square = tensor([[1.3757, 0.7191, 3.2796],
        [0.0051, 0.6021, 1.2616]])
sqrt = tensor([[1.0830, 0.9209,    nan],
        [   nan,    nan, 1.0598]])
ceil = tensor([[ 2.,  1., -1.],
        [-0., -0.,  2.]])
round = tensor([[ 1.,  1., -2.],
        [-0., -1.,  1.]])
clip = tensor([[0.9000, 0.8480, 0.1000],
        [0.1000, 0.1000, 0.9000]])


In [34]:
import torch
b = torch.sqrt(a)
print(b)
print(torch.isnan(b))

tensor([[1.0830, 0.9209,    nan],
        [   nan,    nan, 1.0598]])
tensor([[False, False,  True],
        [ True,  True, False]])


In [35]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print(a)
print(b)
print(a+b)
print(a/b)
print(a ** 2)

tensor([[-0.8212, -0.3027, -0.4340],
        [ 0.1663,  0.0300,  0.8743]])
tensor([[-0.8792,  0.9476, -0.6819],
        [ 0.1332,  0.8845,  1.4165]])
tensor([[-1.7004,  0.6449, -1.1159],
        [ 0.2994,  0.9144,  2.2908]])
tensor([[ 0.9340, -0.3194,  0.6364],
        [ 1.2484,  0.0339,  0.6173]])
tensor([[0.6743, 0.0916, 0.1883],
        [0.0276, 0.0009, 0.7645]])


In [36]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print(torch.matmul(a, b.T))
print(a @ b.T)

tensor([[-2.6604, -0.7280],
        [-0.8797,  0.0326]])
tensor([[-2.6604, -0.7280],
        [-0.8797,  0.0326]])


In [37]:
import torch
a = torch.randn(3)
b = torch.randn(3)
print(a)
print(b)
print(torch.dot(a, b))
print(a @ b)

tensor([-0.8968, -0.7735, -1.7098])
tensor([0.6564, 0.3422, 0.3877])
tensor(-1.5162)
tensor(-1.5162)


In [38]:
import torch
a = torch.randn(3,4)
print(a)
print(torch.mean(a, dim=0))
print(torch.std(a, dim=0))
print(torch.cumsum(a, dim=0))
print(torch.cumprod(a, dim=0))

tensor([[ 0.6987,  0.3769,  0.1178,  0.6638],
        [-0.4769, -1.8749, -0.6628, -1.1807],
        [-0.5660, -0.6108,  0.5689,  0.5388]])
tensor([-0.1147, -0.7029,  0.0080,  0.0073])
tensor([0.7059, 1.1287, 0.6232, 1.0308])
tensor([[ 0.6987,  0.3769,  0.1178,  0.6638],
        [ 0.2218, -1.4980, -0.5451, -0.5169],
        [-0.3442, -2.1088,  0.0239,  0.0219]])
tensor([[ 0.6987,  0.3769,  0.1178,  0.6638],
        [-0.3332, -0.7067, -0.0781, -0.7838],
        [ 0.1886,  0.4316, -0.0444, -0.4223]])


In [39]:
import torch
a = torch.randn(3,4)
print(a)
print(torch.linalg.svd(a))

tensor([[-0.2906, -0.0275,  0.2793, -1.0118],
        [ 0.4705, -0.0978,  0.9259, -1.3871],
        [-0.7481,  0.6195, -0.6975,  0.2261]])
torch.return_types.linalg_svd(
U=tensor([[ 0.4090, -0.5946,  0.6922],
        [ 0.8168, -0.0996, -0.5682],
        [-0.4068, -0.7978, -0.4449]]),
S=tensor([2.1120, 1.0693, 0.2761]),
Vh=tensor([[ 0.2698, -0.1625,  0.5465, -0.7760],
        [ 0.6759, -0.4378,  0.2789,  0.5231],
        [-0.4914, -0.8659, -0.0810, -0.0466],
        [-0.4784,  0.1792,  0.7855,  0.3494]]))


In [40]:
import torch
a = torch.randn(3,4)
b = torch.nn.functional.pad(a, (1,1,0,2), value=0)
print(a)
print(b)

tensor([[ 0.2091,  0.1720, -1.7086,  0.1525],
        [-0.7072,  0.5426, -0.2909, -1.7641],
        [ 1.2363, -0.5535, -0.6034, -0.3002]])
tensor([[ 0.0000,  0.2091,  0.1720, -1.7086,  0.1525,  0.0000],
        [ 0.0000, -0.7072,  0.5426, -0.2909, -1.7641,  0.0000],
        [ 0.0000,  1.2363, -0.5535, -0.6034, -0.3002,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])


In [ ]:
import matplotlib.pyplot as plt
import torch

# create tensors
x = torch.linspace(-1, 1, 100)
y = torch.linspace(-2, 2, 100)
# create the surface
xx, yy = torch.meshgrid(x, y, indexing="xy")  # xy-indexing is matching numpy
z = torch.sqrt(1 - xx**2 - (yy/2)**2)
print(xx)

fig = plt.figure(figsize=(8,8))
ax = plt.axes(projection="3d")
ax.set_xlim([-2, 2])
ax.set_ylim([-2, 2])
ax.set_zlim([0, 2])
ax.plot_surface(xx, yy, z, cmap="cividis")
ax.view_init(45, 35)
plt.show()

tensor([[-1.0000, -0.9798, -0.9596,  ...,  0.9596,  0.9798,  1.0000],
        [-1.0000, -0.9798, -0.9596,  ...,  0.9596,  0.9798,  1.0000],
        [-1.0000, -0.9798, -0.9596,  ...,  0.9596,  0.9798,  1.0000],
        ...,
        [-1.0000, -0.9798, -0.9596,  ...,  0.9596,  0.9798,  1.0000],
        [-1.0000, -0.9798, -0.9596,  ...,  0.9596,  0.9798,  1.0000],
        [-1.0000, -0.9798, -0.9596,  ...,  0.9596,  0.9798,  1.0000]])
