In [1]:
import torch

x = torch.tensor([1, 2, 3])
print(x)
print(x.shape)
print(x.dtype)

tensor([1, 2, 3])
torch.Size([3])
torch.int64


In [2]:
import torch

x = torch.tensor([1., 2., 3.], requires_grad=True)
print(x)
print(x.shape)
print(x.dtype)

tensor([1., 2., 3.], requires_grad=True)
torch.Size([3])
torch.float32


In [3]:
import torch

x = torch.tensor(3.6, requires_grad=True)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [4]:
import numpy as np

polynomial = np.poly1d([1, 2, 3])
print(polynomial)

   2
1 x + 2 x + 3


In [5]:
import numpy as np

polynomial = np.poly1d([1, 2, 3])
print(polynomial(1.5))

8.25


In [6]:
import numpy as np

polynomial = np.poly1d([1, 2, 3])
N = 20   # number of samples

# Generate random samples roughly between -10 to +10
X = np.random.randn(N,1) * 5
Y = polynomial(X)
print(X)
print(Y)

[[ -7.4685948 ]
 [ -1.26102938]
 [ -8.28192305]
 [ -5.6442919 ]
 [ -1.29762172]
 [  8.70972066]
 [ -2.18042289]
 [  1.45856665]
 [ -7.73489404]
 [  0.99133883]
 [ -3.67936245]
 [  5.73819002]
 [  0.41815427]
 [ -0.2619128 ]
 [ -9.38564735]
 [ -4.75439556]
 [  5.27330758]
 [-14.69328684]
 [ -9.80874242]
 [ -4.21651638]]
[[ 43.84271869]
 [  2.06813634]
 [ 55.02640335]
 [ 23.56944725]
 [  2.08857869]
 [ 96.27867538]
 [  3.39339821]
 [  8.04455   ]
 [ 47.35879777]
 [  5.96543032]
 [  9.17898316]
 [ 47.40320469]
 [  4.01116153]
 [  2.54477271]
 [ 72.31908152]
 [ 16.09548606]
 [ 41.35438797]
 [189.50610448]
 [ 79.59394299]
 [ 12.34597762]]


In [7]:
import numpy as np

polynomial = np.poly1d([1, 2, 3])
N = 20   # number of samples

# Generate random samples roughly between -10 to +10
X = np.random.randn(N,1) * 5
Y = polynomial(X)
print(X)
print(Y)

[[  5.99292748]
 [  5.02908741]
 [  5.5244224 ]
 [-11.54937846]
 [  7.80683478]
 [  5.41870306]
 [  1.62930845]
 [ -3.2141396 ]
 [  4.68961673]
 [ -2.29902211]
 [ -9.73266202]
 [  7.29417578]
 [  5.12020222]
 [  2.50024892]
 [ -7.19782536]
 [ -4.86400818]
 [ -3.40102092]
 [ -7.39249651]
 [  1.97486322]
 [  5.8877488 ]]
[[ 50.90103468]
 [ 38.34989496]
 [ 44.56808764]
 [113.2893858 ]
 [ 79.56033892]
 [ 43.19974899]
 [  8.91326295]
 [  6.90241419]
 [ 34.37173852]
 [  3.68745843]
 [ 78.25938604]
 [ 70.79335189]
 [ 39.45687524]
 [ 14.25174249]
 [ 40.41303925]
 [ 16.93055921]
 [  7.76490147]
 [ 42.86401159]
 [ 10.84981117]
 [ 49.44108349]]


In [8]:
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])
N = 20   # number of samples

# Generate random samples roughly between -10 to +10
X = np.random.randn(N,1) * 5
Y = polynomial(X)

# Prepare input as an array of shape (N,3)
XX = np.hstack([X*X, X, np.ones_like(X)])

# Prepare tensors
w = torch.randn(3, 1, requires_grad=True)  # the 3 coefficients
x = torch.tensor(XX, dtype=torch.float32)  # input sample
y = torch.tensor(Y, dtype=torch.float32)   # output sample
optimizer = torch.optim.NAdam([w], lr=0.01)
print(w)

# Run optimizer
for _ in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print(w)

tensor([[-0.0820],
        [-0.4037],
        [ 1.5191]], requires_grad=True)
tensor([[1.0013],
        [2.0016],
        [2.9413]], requires_grad=True)


In [9]:
import random
import torch

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

# Gradient descent loop
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print(A)
print(B)
print(C)
print(D)

tensor(4.2756, requires_grad=True)
tensor(4.7244, requires_grad=True)
tensor(3.7244, requires_grad=True)
tensor(2.7244, requires_grad=True)
