In [1]:
import pandas as pd
data = pd.read_csv("iris.csv", header=None)
X = data.iloc[:, 0:4]
y = data.iloc[:, 4:]

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

data = pd.read_csv("iris.csv", header=None)
X = data.iloc[:, 0:4]
y = data.iloc[:, 4:]

ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False).fit(y)
print(ohe.categories_)

y = ohe.transform(y)
print(y)

[array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]


In [3]:
import torch.nn as nn

class Multiclass(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(4, 8)
        self.act = nn.ReLU()
        self.output = nn.Linear(8, 3)

    def forward(self, x):
        x = self.act(self.hidden(x))
        x = self.output(x)
        return x

model = Multiclass()

In [4]:
import torch.nn as nn

class Multiclass(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(4, 8)
        self.act = nn.ReLU()
        self.output = nn.Linear(8, 3)

    def forward(self, x):
        x = self.act(self.hidden(x))
        x = self.output(x)
        return x

model = Multiclass()

In [5]:
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import tqdm
from sklearn.preprocessing import OneHotEncoder

data = pd.read_csv("iris.csv", header=None)
X = data.iloc[:, 0:4]
y = data.iloc[:, 4:]

ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False).fit(y)
y = ohe.transform(y)

# convert pandas DataFrame (X) and numpy array (y) into PyTorch tensors
X = torch.tensor(X.values, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

class Multiclass(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(4, 8)
        self.act = nn.ReLU()
        self.output = nn.Linear(8, 3)

    def forward(self, x):
        x = self.act(self.hidden(x))
        x = self.output(x)
        return x

model = Multiclass()
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# training parameters
n_epochs = 200
batch_size = 5
batches_per_epoch = len(X) // batch_size

for epoch in range(n_epochs):
    with tqdm.trange(batches_per_epoch, unit="batch", mininterval=0) as bar:
        bar.set_description(f"Epoch {epoch}")
        for i in bar:
            # take a batch
            start = i * batch_size
            X_batch = X[start:start+batch_size]
            y_batch = y[start:start+batch_size]
            # forward pass
            y_pred = model(X_batch)
            loss = loss_fn(y_pred, y_batch)
            # backward pass
            optimizer.zero_grad()
            loss.backward()
            # update weights
            optimizer.step()

Epoch 101:  37%|███▋      | 11/30 [00:00<00:00, 438.83batch/s]


KeyboardInterrupt: 

In [6]:
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

# read data and apply one-hot encoding
data = pd.read_csv("iris.csv", header=None)
X = data.iloc[:, 0:4]
y = data.iloc[:, 4:]
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False).fit(y)
y = ohe.transform(y)

# convert pandas DataFrame (X) and numpy array (y) into PyTorch tensors
X = torch.tensor(X.values, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

# split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, shuffle=True)

In [7]:
import copy

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import tqdm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

# read data and apply one-hot encoding
data = pd.read_csv("iris.csv", header=None)
X = data.iloc[:, 0:4]
y = data.iloc[:, 4:]
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False).fit(y)
y = ohe.transform(y)

# convert pandas DataFrame (X) and numpy array (y) into PyTorch tensors
X = torch.tensor(X.values, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

# split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, shuffle=True)

class Multiclass(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(4, 8)
        self.act = nn.ReLU()
        self.output = nn.Linear(8, 3)

    def forward(self, x):
        x = self.act(self.hidden(x))
        x = self.output(x)
        return x

# loss metric and optimizer
model = Multiclass()
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# prepare model and training parameters
n_epochs = 200
batch_size = 5
batches_per_epoch = len(X_train) // batch_size

best_acc = - np.inf   # init to negative infinity
best_weights = None
train_loss_hist = []
train_acc_hist = []
test_loss_hist = []
test_acc_hist = []

# training loop
for epoch in range(n_epochs):
    epoch_loss = []
    epoch_acc = []
    # set model in training mode and run through each batch
    model.train()
    with tqdm.trange(batches_per_epoch, unit="batch", mininterval=0) as bar:
        bar.set_description(f"Epoch {epoch}")
        for i in bar:
            # take a batch
            start = i * batch_size
            X_batch = X_train[start:start+batch_size]
            y_batch = y_train[start:start+batch_size]
            # forward pass
            y_pred = model(X_batch)
            loss = loss_fn(y_pred, y_batch)
            # backward pass
            optimizer.zero_grad()
            loss.backward()
            # update weights
            optimizer.step()
            # compute and store metrics
            acc = (torch.argmax(y_pred, 1) == torch.argmax(y_batch, 1)).float().mean()
            epoch_loss.append(float(loss))
            epoch_acc.append(float(acc))
            bar.set_postfix(
                loss=float(loss),
                acc=float(acc)
            )
    # set model in evaluation mode and run through the test set
    model.eval()
    y_pred = model(X_test)
    ce = loss_fn(y_pred, y_test)
    acc = (torch.argmax(y_pred, 1) == torch.argmax(y_test, 1)).float().mean()
    ce = float(ce)
    acc = float(acc)
    train_loss_hist.append(np.mean(epoch_loss))
    train_acc_hist.append(np.mean(epoch_acc))
    test_loss_hist.append(ce)
    test_acc_hist.append(acc)
    if acc > best_acc:
        best_acc = acc
        best_weights = copy.deepcopy(model.state_dict())
    print(f"Epoch {epoch} validation: Cross-entropy={ce:.2f}, Accuracy={acc*100:.1f}%")

# Restore best model
model.load_state_dict(best_weights)

# Plot the loss and accuracy
plt.plot(train_loss_hist, label="train")
plt.plot(test_loss_hist, label="test")
plt.xlabel("epochs")
plt.ylabel("cross entropy")
plt.legend()
plt.show()

plt.plot(train_acc_hist, label="train")
plt.plot(test_acc_hist, label="test")
plt.xlabel("epochs")
plt.ylabel("accuracy")
plt.legend()
plt.show()

Epoch 0: 100%|██████████| 21/21 [00:00<00:00, 309.22batch/s, acc=0.4, loss=1.01] 


Epoch 0 validation: Cross-entropy=1.00, Accuracy=37.8%


Epoch 1: 100%|██████████| 21/21 [00:00<00:00, 298.13batch/s, acc=0.8, loss=0.963]


Epoch 1 validation: Cross-entropy=0.96, Accuracy=68.9%


Epoch 2: 100%|██████████| 21/21 [00:00<00:00, 374.83batch/s, acc=0.8, loss=0.916]


Epoch 2 validation: Cross-entropy=0.91, Accuracy=71.1%


Epoch 3: 100%|██████████| 21/21 [00:00<00:00, 375.00batch/s, acc=0.8, loss=0.867]


Epoch 3 validation: Cross-entropy=0.88, Accuracy=75.6%


Epoch 4: 100%|██████████| 21/21 [00:00<00:00, 374.88batch/s, acc=1, loss=0.824]  


Epoch 4 validation: Cross-entropy=0.83, Accuracy=97.8%


Epoch 5: 100%|██████████| 21/21 [00:00<00:00, 328.01batch/s, acc=1, loss=0.786]  


Epoch 5 validation: Cross-entropy=0.80, Accuracy=97.8%


Epoch 6: 100%|██████████| 21/21 [00:00<00:00, 328.12batch/s, acc=1, loss=0.751]  


Epoch 6 validation: Cross-entropy=0.77, Accuracy=95.6%


Epoch 7: 100%|██████████| 21/21 [00:00<00:00, 327.99batch/s, acc=1, loss=0.719]  


Epoch 7 validation: Cross-entropy=0.74, Accuracy=95.6%


Epoch 8: 100%|██████████| 21/21 [00:00<00:00, 374.96batch/s, acc=1, loss=0.689]  


Epoch 8 validation: Cross-entropy=0.72, Accuracy=95.6%


Epoch 9: 100%|██████████| 21/21 [00:00<00:00, 313.44batch/s, acc=1, loss=0.661]  


Epoch 9 validation: Cross-entropy=0.69, Accuracy=95.6%


Epoch 10: 100%|██████████| 21/21 [00:00<00:00, 323.35batch/s, acc=1, loss=0.636]  


Epoch 10 validation: Cross-entropy=0.67, Accuracy=97.8%


Epoch 11: 100%|██████████| 21/21 [00:00<00:00, 334.92batch/s, acc=1, loss=0.612]  


Epoch 11 validation: Cross-entropy=0.65, Accuracy=97.8%


Epoch 12: 100%|██████████| 21/21 [00:00<00:00, 328.24batch/s, acc=1, loss=0.59]   


Epoch 12 validation: Cross-entropy=0.63, Accuracy=97.8%


Epoch 13: 100%|██████████| 21/21 [00:00<00:00, 327.28batch/s, acc=1, loss=0.569]  


Epoch 13 validation: Cross-entropy=0.61, Accuracy=97.8%


Epoch 14: 100%|██████████| 21/21 [00:00<00:00, 289.37batch/s, acc=1, loss=0.55]   


Epoch 14 validation: Cross-entropy=0.59, Accuracy=97.8%


Epoch 15: 100%|██████████| 21/21 [00:00<00:00, 309.44batch/s, acc=1, loss=0.533]  


Epoch 15 validation: Cross-entropy=0.57, Accuracy=97.8%


Epoch 16: 100%|██████████| 21/21 [00:00<00:00, 341.93batch/s, acc=1, loss=0.517]  


Epoch 16 validation: Cross-entropy=0.56, Accuracy=97.8%


Epoch 17: 100%|██████████| 21/21 [00:00<00:00, 278.04batch/s, acc=1, loss=0.502]  


Epoch 17 validation: Cross-entropy=0.54, Accuracy=97.8%


Epoch 18: 100%|██████████| 21/21 [00:00<00:00, 273.45batch/s, acc=1, loss=0.489]  


Epoch 18 validation: Cross-entropy=0.53, Accuracy=97.8%


Epoch 19: 100%|██████████| 21/21 [00:00<00:00, 334.94batch/s, acc=1, loss=0.475] 


Epoch 19 validation: Cross-entropy=0.51, Accuracy=97.8%


Epoch 20: 100%|██████████| 21/21 [00:00<00:00, 327.40batch/s, acc=1, loss=0.463]  


Epoch 20 validation: Cross-entropy=0.50, Accuracy=97.8%


Epoch 21: 100%|██████████| 21/21 [00:00<00:00, 326.57batch/s, acc=1, loss=0.451]  


Epoch 21 validation: Cross-entropy=0.49, Accuracy=97.8%


Epoch 22: 100%|██████████| 21/21 [00:00<00:00, 349.55batch/s, acc=1, loss=0.441]  


Epoch 22 validation: Cross-entropy=0.48, Accuracy=97.8%


Epoch 23: 100%|██████████| 21/21 [00:00<00:00, 330.60batch/s, acc=1, loss=0.431]  


Epoch 23 validation: Cross-entropy=0.47, Accuracy=97.8%


Epoch 24: 100%|██████████| 21/21 [00:00<00:00, 341.78batch/s, acc=1, loss=0.422]  


Epoch 24 validation: Cross-entropy=0.46, Accuracy=97.8%


Epoch 25: 100%|██████████| 21/21 [00:00<00:00, 252.12batch/s, acc=1, loss=0.414]  


Epoch 25 validation: Cross-entropy=0.45, Accuracy=97.8%


Epoch 26: 100%|██████████| 21/21 [00:00<00:00, 343.85batch/s, acc=1, loss=0.405]  


Epoch 26 validation: Cross-entropy=0.44, Accuracy=97.8%


Epoch 27: 100%|██████████| 21/21 [00:00<00:00, 348.43batch/s, acc=1, loss=0.398]  


Epoch 27 validation: Cross-entropy=0.43, Accuracy=97.8%


Epoch 28: 100%|██████████| 21/21 [00:00<00:00, 341.71batch/s, acc=1, loss=0.391]  


Epoch 28 validation: Cross-entropy=0.43, Accuracy=97.8%


Epoch 29: 100%|██████████| 21/21 [00:00<00:00, 346.99batch/s, acc=1, loss=0.384]  


Epoch 29 validation: Cross-entropy=0.42, Accuracy=97.8%


Epoch 30: 100%|██████████| 21/21 [00:00<00:00, 361.71batch/s, acc=1, loss=0.376]  


Epoch 30 validation: Cross-entropy=0.41, Accuracy=97.8%


Epoch 31: 100%|██████████| 21/21 [00:00<00:00, 398.02batch/s, acc=1, loss=0.37]   


Epoch 31 validation: Cross-entropy=0.41, Accuracy=100.0%


Epoch 32: 100%|██████████| 21/21 [00:00<00:00, 421.50batch/s, acc=1, loss=0.364]  


Epoch 32 validation: Cross-entropy=0.40, Accuracy=100.0%


Epoch 33: 100%|██████████| 21/21 [00:00<00:00, 368.92batch/s, acc=1, loss=0.358]  


Epoch 33 validation: Cross-entropy=0.39, Accuracy=100.0%


Epoch 34: 100%|██████████| 21/21 [00:00<00:00, 413.02batch/s, acc=1, loss=0.352]  


Epoch 34 validation: Cross-entropy=0.39, Accuracy=100.0%


Epoch 35: 100%|██████████| 21/21 [00:00<00:00, 341.16batch/s, acc=1, loss=0.347]  


Epoch 35 validation: Cross-entropy=0.38, Accuracy=100.0%


Epoch 36: 100%|██████████| 21/21 [00:00<00:00, 405.37batch/s, acc=1, loss=0.341]  


Epoch 36 validation: Cross-entropy=0.37, Accuracy=100.0%


Epoch 37: 100%|██████████| 21/21 [00:00<00:00, 382.43batch/s, acc=1, loss=0.336]  


Epoch 37 validation: Cross-entropy=0.37, Accuracy=100.0%


Epoch 38: 100%|██████████| 21/21 [00:00<00:00, 416.99batch/s, acc=1, loss=0.331]  


Epoch 38 validation: Cross-entropy=0.36, Accuracy=100.0%


Epoch 39: 100%|██████████| 21/21 [00:00<00:00, 371.78batch/s, acc=1, loss=0.326]  


Epoch 39 validation: Cross-entropy=0.36, Accuracy=100.0%


Epoch 40: 100%|██████████| 21/21 [00:00<00:00, 377.99batch/s, acc=1, loss=0.322]  


Epoch 40 validation: Cross-entropy=0.35, Accuracy=100.0%


Epoch 41: 100%|██████████| 21/21 [00:00<00:00, 366.12batch/s, acc=1, loss=0.317]  


Epoch 41 validation: Cross-entropy=0.35, Accuracy=100.0%


Epoch 42: 100%|██████████| 21/21 [00:00<00:00, 370.71batch/s, acc=1, loss=0.313]  


Epoch 42 validation: Cross-entropy=0.34, Accuracy=100.0%


Epoch 43: 100%|██████████| 21/21 [00:00<00:00, 403.39batch/s, acc=1, loss=0.308]  


Epoch 43 validation: Cross-entropy=0.34, Accuracy=100.0%


Epoch 44: 100%|██████████| 21/21 [00:00<00:00, 371.39batch/s, acc=1, loss=0.304]  


Epoch 44 validation: Cross-entropy=0.33, Accuracy=100.0%


Epoch 45:  62%|██████▏   | 13/21 [00:00<00:00, 326.63batch/s, acc=0.8, loss=0.526]


KeyboardInterrupt: 